// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_DkQHl9rxUG28gBHeK0J7tZlHhaZIJU',
    appId: '1:1030446710608:web:da86b1128ed91b08037655',
    messagingSenderId: '1030446710608',
    projectId: 'pokecode-445e0',
    authDomain: 'pokecode-445e0.firebaseapp.com',
    storageBucket: 'pokecode-445e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESd-RC6v4tAAVVvrabLLqEfACL3HWF-c',
    appId: '1:1030446710608:android:40fff8e3cd80bcb5037655',
    messagingSenderId: '1030446710608',
    projectId: 'pokecode-445e0',
    storageBucket: 'pokecode-445e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5J7K0skidKy66Nylj9SuS1C81YI1n74',
    appId: '1:1030446710608:ios:e1cf32b0ff651c96037655',
    messagingSenderId: '1030446710608',
    projectId: 'pokecode-445e0',
    storageBucket: 'pokecode-445e0.appspot.com',
    iosClientId: '1030446710608-kgvmld08bcois0paql3ghgudk1b12tns.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu5J7K0skidKy66Nylj9SuS1C81YI1n74',
    appId: '1:1030446710608:ios:342f9cbdb058c581037655',
    messagingSenderId: '1030446710608',
    projectId: 'pokecode-445e0',
    storageBucket: 'pokecode-445e0.appspot.com',
    iosClientId: '1030446710608-t2n1bngubdjp2f9fj1qrj1h3geoq6i3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokecode.RunnerTests',
  );
}
