// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-5C823C6NhbnlW8feIMQXvnpSK2n4VM',
    appId: '1:270990256178:web:42e920a765a63eb755342b',
    messagingSenderId: '270990256178',
    projectId: 'pokecode-ufrpe',
    authDomain: 'pokecode-ufrpe.firebaseapp.com',
    databaseURL: 'https://pokecode-ufrpe-default-rtdb.firebaseio.com',
    storageBucket: 'pokecode-ufrpe.appspot.com',
    measurementId: 'G-BYSM2DJ6M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD0w1MjWo4NUWTRXqEsaZkB6S_DNhHY1Q',
    appId: '1:270990256178:android:1459a0d96e23171e55342b',
    messagingSenderId: '270990256178',
    projectId: 'pokecode-ufrpe',
    databaseURL: 'https://pokecode-ufrpe-default-rtdb.firebaseio.com',
    storageBucket: 'pokecode-ufrpe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6bN3ahpcUxWrvfp8baaWnWDeJvn3Lis',
    appId: '1:270990256178:ios:cf109026b537c0ea55342b',
    messagingSenderId: '270990256178',
    projectId: 'pokecode-ufrpe',
    databaseURL: 'https://pokecode-ufrpe-default-rtdb.firebaseio.com',
    storageBucket: 'pokecode-ufrpe.appspot.com',
    iosClientId: '270990256178-5ckuna4p5qnh3ttutcj9pe9jhsc8noaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6bN3ahpcUxWrvfp8baaWnWDeJvn3Lis',
    appId: '1:270990256178:ios:9b771e3dbbfc714b55342b',
    messagingSenderId: '270990256178',
    projectId: 'pokecode-ufrpe',
    databaseURL: 'https://pokecode-ufrpe-default-rtdb.firebaseio.com',
    storageBucket: 'pokecode-ufrpe.appspot.com',
    iosClientId: '270990256178-eoa93cqf5v302bjlrigbnh1pgb6f8sps.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokecode.RunnerTests',
  );
}
